# Changes here will be overwritten by Copier
_commit: v0.7.0
_src_path: https://github.com/fohte/generic-boilerplate
description: Container image build for octo-sts
is_public: true
project_name: docker-octo-sts
repo_language: en
subpackages: []
type: base
use_release_please: false
